### ISSUE TITLE
Provisioning module should take vlan and network_domain names

### ISSUE THREAD

**Issue by jadunham1** [DimensionDataDevOps/ansible-dimensiondata#12]
Right now it only takes vlan_ids and network_domain_ids.
This kind of stinks for a user experience.
We need to be able to handle both.

**Comment by aimonb** [comment]
We can do a lookup. For the Firewall module I accept both and detect if UUID. If it isn't valid UUID then I search for the rule and get ID.

**Comment by aimonb** [comment]
Fixed with https://github.com/DimensionDataDevOps/ansible-dimensiondata/pull/23
