### ISSUE TITLE
Create VM not idempotent

### ISSUE THREAD

**Issue by aimonb** [DimensionDataDevOps/ansible-dimensiondata#9]
Create VM appears to crete a new VM with the same name on every run. Is there a way to ensure it does not recreate it?

**Comment by jadunham1** [comment]
Yes, there is a field called unique_names
If you have "yes/true" it will not create a VM with the same name in DD cloud.

Does this satisfy the request?

**Comment by aimonb** [comment]
Yes absolutely! I haven't actually looked at the code yet, colleague reported it to me. I will pas the info along.
